import localFont from "next/font/local";
import "./globals.css";
import Chatbot from "./components/Chatbot"
import { UserProvider } from "@auth0/nextjs-auth0/client";

// Local fonts configuration
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata
export const metadata = {
  title: "AuctionArchitects",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
          <Chatbot />
        </body>
      </UserProvider>
    </html>
  );
}
